### PR TITLE
[Damask] update import names

### PR DESCRIPTION
**Pull request by samwaseda**
From the recent development in DAMASK it looked to me like the names had to be changed this way

### CODE REVIEW

**Comment by jan-janssen** [comment]
@samwaseda  You also have to update the damask version in https://github.com/pyiron/pyiron_continuum/blob/main/.ci_support/environment-notebooks.yml

**Comment by yangbai90** [comment]
Hi all, I think this should also be considered for the  'import': 6e2ff0412da9ef6b81418c4e4c8d9a3ec02e74c6. The `imp` is not necessary anymore, maybe we could remove it.

**Comment by samwaseda** [comment]
Hm I don't quite understand why the tests are failing

**Comment by samwaseda** [comment]
Ok now I understood that there's a conflict between fenics and damask, and I didn't see the problem on my local installation because I don't have fenics. Do you want to take a look? @mbruns91

**Comment by mbruns91** [comment]
Apparently, the environment created from `.ci_support/environment-notebooks.yml` cannot be solved, as the requirements imposed by packages `damask` and `fenics` are incompatibel. I'll follow a suggestion from @samwaseda and split this file into one for the the damask and another for the fencis notebooks.

**Comment by mbruns91** [comment]
(writing all of this down here, kind of servs as a reminder for me, as I won't be able to work continuously on this today)

Next step would be to run integration tests now seperately for the damask- and the fenics-based notebooks. This requires changes to some files in `.github/workflows/` and also to `.ci_support/build_notebooks.sh`.

I think this makes sense, as we can then at least guarantee, that a user wanting to run fenics/damask only, can be sure that works. Having access to both from the same environment will, however, not be supported at this point.

**Comment by mbruns91** [comment]
Ok, that was unsuccessful. the changes from my commits need to be merged into main first for the ci to change. I'll open another branch and PR for that.

**Pull request merged**
