### PR TITLE
Damask create integration tests

### PR DESCRIPTION
**Pull request by samwaseda**
Before I work too much on [this PR](https://github.com/pyiron/pyiron_continuum/pull/276), I created this PR to include integration tests for backward compatibility.

### CODE REVIEW

**Comment by samwaseda** [comment]
@niklassiemer @mbruns91 Since the Damask jobs are very heavy, I wanted them to run only when `integration` is added, just like the integration tests in `pyiron_base`. I copied and pasted [these lines](https://github.com/pyiron/pyiron_base/blob/e50f885928a081eaf9d7243ac86e1c6df15a9f03/.github/workflows/atomistics-compat.yml#L14-L16). Did I do it correctly?

**Review by niklassiemer — COMMENTED** [review]
The modifications of the actions seems reasonable :) I wonder why we do not use caches to capture the conda builds. though. However, this is probably for another PR.

**Comment by liamhuber** [comment]
> I wonder why we do not use caches to capture the conda builds. though. However, this is probably for another PR.

Don't forget, the centralized actions are not all-or-nothing!

```
   - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: "3.11"
        mamba-version: "*"
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true
        environment-file: .ci_support/environment.yml
```

Could be replaced with the [`cached-mamba` action](https://github.com/pyiron/actions/blob/main/cached-mamba/action.yml), looking shorter and gaining caching with a syntax like this

```
  - uses: pyiron/actions/cached-mamba@main
    with:
      python-version: "3.11"
      env-prefix: "ubuntu-latest"
      env-label: "ubuntue-latest-py-3.11"
      env-files: .ci_support/environment.yml
```

**Review by mbruns91 — COMMENTED** [review]
lgtm

**Pull request merged**
