### PR TITLE
Move tests around

### PR DESCRIPTION
**Pull request by liamhuber**
Move tests to split apart unit and integration more clearly

### CODE REVIEW

**Comment by liamhuber** [comment]
I don't understand how the integration tests fail (`AttributeError: module 'fenics' has no attribute 'UnitSquareMesh'`) when the notebook tests pass, and they do the same thing with the same environment...

**Comment by liamhuber** [comment]
@muh-hassani when you get a minute could you please look at the CI input for me? In both notebook and integration tests I have the line `pr.create.job.Fenics`; for notebooks it runs fine in the notebooks but crashes for the integration tests with ```AttributeError: module 'fenics' has no attribute 'UnitSquareMesh'```. 

I tried making `.github/integrationtest.yml` more and more like `.github/notebooks.yml` but without effect. I'm not sure why integration failed to begin with, and now that the CI setup looks exactly like the passing notebooks I *really* don't get it. 

The "right" solution in my head is that the integration tests are running a different version of fenics where `UnitSquareMesh` has a different name or location, but I don't see anything that would cause the different tests to have different versions.

**Comment by muh-hassani** [comment]
@liamhuber, I tried to make both workflows similar, but it seems that it is not something trivial. I have to look deeper. Strangely, now the unittests also fails:
```
FAIL: test_p (elasticity.test_eschelby.TestEschelby)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/tests/unit/elasticity/test_eschelby.py", line 21, in test_p
    self.assertTrue(
AssertionError: False is not true : p-matrix has a full dimension

```
I will try locally the integration test, with the same environment and see whether there has been some changes in FEniCs, which I doubt!

**Comment by liamhuber** [comment]
@muh-hassani ayayay, it is not great that the elasticity stuff is also having trouble now!

Yeah, on my local machine the integration tests run fine. I haven't booted up the notebooks and run them, but those are passing on the CI anyhow so I'm not worried about it. It really seems to be an env issue with the integration CI but I'm super confused where it's coming from.

**Comment by muh-hassani** [comment]
@liamhuber it is crazy but rerunning the unittest workflow without any change was successful!

**Comment by liamhuber** [comment]
> @liamhuber it is crazy but rerunning the unittest workflow without any changes was successful!

😬 scary.

This is crazy. I see your debugs, and I just don't get how this can be the case when the notebooks run! This is madness, things are either insanely broken or we're missing something super simple.

**Comment by muh-hassani** [comment]
@liamhuber it was too simple, I believe! I think that the problem was that the directory which contained the tests. It was named fenics as well, and the tests could not find the attribute within this directory/module. I changed it to fenics_tests. I think it should run fine this time.

**Comment by liamhuber** [comment]
> I changed it to fenics_tests.

@muh-hassani wonderful! Thank you! That is simultaneously super relieving and pretty embarrassing. Still, at the end of the day I'm glad it's resolved and it's a nice gotcha to remember for future test directory setups.

**Pull request merged**
