### PR TITLE
Use datacontainer

### LINKED ISSUE #111: Using input datacontainer for the refactored attributes in damask job
Currently we use 
```
 pr.continuum.damask.Homogenization(...)
# or
 pr.continuum.damask.Elasticity(...)
#or
 pr.continuum.damask.Plasticity(...)
```
it would be better to change it to:
```
job.input.elasticity(...)
job.input.plasticity(...)
job.input.homogenization(...)
```
I can assume that to_hdf(), and from_hdf() might be an issue in the above case, if it is the case, we can use:

```
job.elasticity(...)
job.plasticity(...)
job.homogenization(...)
```

### PR DESCRIPTION
**Pull request by srmnitc**
Close #111 

I have mostly assigned everything to datacontainer. I have updated `notebooks/damask_tutorial_elastoplasticity-isotropic.ipynb` to reflect the changes. 

There are two issues: rotation and grid; they both are difficult to serialize; hence I do not store them in datacontainer. Therefore, we would also have trouble reading it back in. @muh-hassani I would like some feedback here.

### CODE REVIEW

**Comment by samwaseda** [comment]
@srmnitc showed not much interest in this branch but I find it useful so I push it ahead

**Comment by srmnitc** [comment]
> @srmnitc did not show much interest in this branch but I find it useful so I push it ahead

Glad that it will end up being useful, after all

**Comment by samwaseda** [comment]
It looks like I have a problem now with the Damask unit tests, because Damask is not installed for the unit tests. @mbruns91: Would you be able to take a look?

**Comment by mbruns91** [comment]
Sure, I'll look into it.

**Comment by samwaseda** [comment]
I'm gonna merge this one as soon as the tests pass, because I'm sure no one's gonna review it XD

**Pull request merged**
