### PR TITLE
Try Python 3.10

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
Damask is not available for Python 3.10 in particular the older Damask version we use: 
```
 Encountered problems while solving:
835
    - package damask-3.0.0a4-py37h33b5f3a_16 requires python-damask 3.0.0a4 py37h89c1867_16, but none of the providers can be installed
```

**Comment by jan-janssen** [comment]
Waiting for https://github.com/conda-forge/damask-feedstock/pull/129

**Comment by jan-janssen** [comment]
The Python 3.10 version of Damask was just released, so we just have to update the pyiron Damask interface.

**Comment by muh-hassani** [comment]
The interface will be updated by https://github.com/pyiron/pyiron_continuum/pull/87. I have one single issue. I will fix it tonight.

**Comment by jan-janssen** [comment]
> The interface will be updated by #87. I have one single issue. I will fix it tonight.

There still seems to be issues with the conda packages.

**Comment by jan-janssen** [comment]
It seems to be a `fenics` error or at least `fenics` for python 3.10 is not compatible to the other packages.

**Comment by muh-hassani** [comment]
> It seems to be a `fenics` error or at least `fenics` for python 3.10 is not compatible to the other packages.

During running fenics notebooks, it complains FEN is not found, though fenics 

> It seems to be a `fenics` error or at least `fenics` for python 3.10 is not compatible to the other packages.

As far as I understood, both `fenics` and `mshr` are available for python 3.10, but they are commented out in the `environment-notebook.yml`. Shall we uncomment them?

**Comment by jan-janssen** [comment]
> As far as I understood, both `fenics` and `mshr` are available for python 3.10, but they are commented out in the `environment-notebook.yml`. Shall we uncomment them?

Then the environment can not be resolved - that is what I tried above.

**Comment by jan-janssen** [comment]
Maybe try:
```
- fenics =2019.1.0=*_34
- mshr =2019.1.0=*_6
```

**Comment by jan-janssen** [comment]
```
papermill.exceptions.PapermillExecutionError: 
[40](https://github.com/pyiron/pyiron_continuum/actions/runs/4081075362/jobs/7034145595#step:5:41)
---------------------------------------------------------------------------
[41](https://github.com/pyiron/pyiron_continuum/actions/runs/4081075362/jobs/7034145595#step:5:42)
Exception encountered at "In [22]":
[42](https://github.com/pyiron/pyiron_continuum/actions/runs/4081075362/jobs/7034145595#step:5:43)
---------------------------------------------------------------------------
[43](https://github.com/pyiron/pyiron_continuum/actions/runs/4081075362/jobs/7034145595#step:5:44)
TypeError                                 Traceback (most recent call last)
[44](https://github.com/pyiron/pyiron_continuum/actions/runs/4081075362/jobs/7034145595#step:5:45)
Cell In[22], line 1
[45](https://github.com/pyiron/pyiron_continuum/actions/runs/4081075362/jobs/7034145595#step:5:46)
----> 1 job.output.damask.view(what='increment',datasets=80)
[46](https://github.com/pyiron/pyiron_continuum/actions/runs/4081075362/jobs/7034145595#step:5:47)

[47](https://github.com/pyiron/pyiron_continuum/actions/runs/4081075362/jobs/7034145595#step:5:48)
TypeError: Result.view() got an unexpected keyword argument 'what'
[48](https://github.com/pyiron/pyiron_continuum/actions/runs/4081075362/jobs/7034145595#step:5:49)

[49](https://github.com/pyiron/pyiron_continuum/actions/runs/4081075362/jobs/7034145595#step:5:50)
Input Notebook:  ./damask_tutorial_elastoplasticity-isotropic.ipynb
```

**Pull request merged**
