### PR TITLE
Centralize notebook run

### PR DESCRIPTION
**Pull request by liamhuber**
Replace the bespoke notebooks script with the centralize `pyiron/actions/build-notebooks`.

Pros:
- +7, -37
- Updated action versions
- Automatically leverages caching for the environment
- Single-source of truth for `build_notebooks.sh`, and increased power that comes with this other, more up-to-date version of that script (I'll stack another PR to show this)
- Runs on stacked PRs (this is unrelated to centralization, just something extra I slipped in)

Cons:
- One level of misdirection

### CODE REVIEW

**Comment by liamhuber** [comment]
`notebooks/damask_tutorial_multiplerolling.ipynb`, `notebooks/damask_tutorial_elastoplasticity-isotropic.ipynb`, `notebooks/damask_tutorial_elastoplasticity-powerlaw.ipynb`, and `notebooks/damask_tutorial.ipynb` all fail with the error:

```
Executing:   0%|          | 0/28 [00:00<?, ?cell/s]Kernelspec name pyiron cannot be found!
No such kernel named pyiron
```

I see that in the `build_notebooks.sh` script I deleted, the papermill invokation specifically forces the kernel to `-k "python3"`. Maybe this is to overcome some undesirable kernel specification already saved in the notebooks? The problem seems specific to the damask notebooks, and the rest of this transition went as I expected, so I don't think there's anything explicitly wrong with the centralized CI here.

**Comment by liamhuber** [comment]
@samwaseda @mbruns91, opening and immediately saving the offending damask notebooks did the trick for the CI -- my jupyterlab automatically switched the kernel to `python3`. Was saving the notebooks with the `pyiron` kernel critical for some other part of your infrastructure, or is this just some weird artifact of someone's particular dev environment?

I'm open to adding the `-k "python3"` line to the centralized script, but I want to understand better what's going on before taking any action.

**Review by samwaseda — APPROVED** [review]
It would be nice to solve [this problem](https://github.com/pyiron/pyiron_continuum/issues/311) beforehand but even without I'm happy with the current version

**Review by mbruns91 — APPROVED** [review]
lgtm 👍

**Comment by mbruns91** [comment]
> @samwaseda @mbruns91, opening and immediately saving the offending damask notebooks did the trick for the CI -- my jupyterlab automatically switched the kernel to `python3`. Was saving the notebooks with the `pyiron` kernel critical for some other part of your infrastructure, or is this just some weird artifact of someone's particular dev environment?
> 
> I'm open to adding the `-k "python3"` line to the centralized script, but I want to understand better what's going on before taking any action.

I'm quite sure the usage of a `pyiron` kernel is just some artifact. Using a more general `python3` kernel (which is supposedly available in more or less any vanilla jupyter env) is definitely a better idea in my opinion.

**Review by mbruns91 — APPROVED** [review]

**Comment by liamhuber** [comment]
@mbruns91 in #312 in the [commit where you flattened the notebooks](https://github.com/pyiron/pyiron_continuum/pull/312/commits/c791de08c4ca9590c3ec9f35361f2775662fec83), the open phase directory also got committed. Heads-up: I'm going to remove it from this PR.

**Comment by mbruns91** [comment]
Oh, this was totally unintended. Thanks for noticing and removing 👍

**Pull request merged**
