### PR TITLE
Accelerate conda CI using mamba

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
```
/usr/share/miniconda/envs/test/lib/python3.9/site-packages/pyiron_continuum/fenics/job/generic.py in <module>
319
      8 
320
      9 import fenics as FEN
321
---> 10 import mshr
322
     11 import sympy
323
     12 from pyiron_base import GenericJob, DataContainer
324

325
/usr/share/miniconda/envs/test/lib/python3.9/site-packages/mshr/__init__.py in <module>
326
     22 import dolfin
327
     23 
328
---> 24 from .cpp import Circle
329
     25 from .cpp import Ellipse
330
     26 from .cpp import Rectangle
331

332
ImportError: generic_type: type "CSGGeometry" referenced unknown base type "dolfin::Variable"
```

**Comment by jan-janssen** [comment]
@muh-hassani There seems to be an issue with the latest version of fenics.

**Comment by muh-hassani** [comment]
There has been no new build for mshr and fenics on conda-forge. @jan-janssen the error is really strange. I remember that after the build 2019.1.0=*_2, this error was fixed. I will look more into this.

**Comment by muh-hassani** [comment]
After pinning fenics and mshr to the latest cond-forge builds, the tests ran successfully.

**Comment by jan-janssen** [comment]
@muh-hassani Thanks a lot for taking a look at this. Then I guess it is ready to be merged now.

**Pull request merged**
