### PR TITLE
Update output

### PR DESCRIPTION
**Pull request by Ahmed-Aslam**

### CODE REVIEW

**Review by liamhuber — COMMENTED** [review]
It looks like you are reverting from using DataContainer for output to using GenericParameters for output-- is this the case? If so why?

**Comment by Ahmed-Aslam** [comment]
> It looks like you are reverting from using DataContainer for output to using GenericParameters for output-- is this the case? If so why?
Yes, In previous version, I used DataContainer. But, the output was not reflected in job.output. Therefore, I have reverted to Generic implementation. Can you please comment if this [https://github.com/pyiron/pyiron_continuum/pull/57/files#diff-7384e555bed4e72dd9d1d766df0a154957d47a6b4938e4697df4c8fe10b87e6fL60-L63] was the correct way to do it?

**Comment by liamhuber** [comment]
I will take a look later this morning. GenericParameters is on its way to the graveyard though so I really want to avoid this change.

Can you please explain in a bit more detail what is meant by the output not being reflected?

**Comment by pmrv** [comment]
It seems you [previously](https://github.com/pyiron/pyiron_continuum/blob/69dcff561e0d72409308c50c050314fbe17998bf/pyiron_continuum/damask/damaskjob.py) never wrote the `input` and `output` containers to HDF (by calling their `.to_hdf`).  This is why after reloading jobs they cannot reflect output previously collected.  You should add `to_hdf` and `from_hdf` (preferably after [this](https://github.com/pyiron/pyiron_base/pull/416/commits/0f7cc6abe587c333015a67dc03824be5be9b6acf) is merged and pyiron_base is on the next version), that do the following things
1. call `super()._to_hdf`
2. call `self.input.to_hdf(...)`
3. call `self.output.to_hdf(...)`
Same for `from_hdf`.  Writing output might also be necessary in `collect_output`, will test that right now.

**Comment by liamhuber** [comment]
Super, yes I think Marvin hit the nail on the head. Implementing `to_hdf` and `from_hdf` routines and then invoking `to_hdf` in `collect_output` should do the trick.

A couple of Gotchas:
- Instead of `self.input = DataContainer()` use `self.input = DataContainer(table_name='dc_input')`. Hopefully this won't be necessary in the future, but right now that stops the data container for conflicting with the `GenericJob.to_hdf` call that already writes to the HDF path `input`.
- When calling data container `to_hdf` methods, pass the job's `project_hdf5` as the argument, i.e. `self.input.to_hdf(hdf=self.project_hdf5)`

@pmrv please quickly read and let us know if I'm spouting nonsense here ;)

**Comment by pmrv** [comment]
> Super, yes I think Marvin hit the nail on the head. Implementing `to_hdf` and `from_hdf` routines and then invoking `to_hdf` in `collect_output` should do the trick.
> 
> A couple of Gotchas:
> 
>     * Instead of `self.input = DataContainer()` use `self.input = DataContainer(table_name='dc_input')`. Hopefully this won't be necessary in the future, but right now that stops the data container for conflicting with the `GenericJob.to_hdf` call that already writes to the HDF path `input`.
> 
>     * When calling data container `to_hdf` methods, pass the job's `project_hdf5` as the argument, i.e. `self.input.to_hdf(hdf=self.project_hdf5)`
> 
> 
> @pmrv please quickly read and let us know if I'm spouting nonsense here ;)

Sounds good!

**Comment by Ahmed-Aslam** [comment]
Thank you. I will update this.

**Comment by pmrv** [comment]
Also don't hesitate to ping me in the future if problems like this pop up, before you sink a lot of time into it.

**Comment by Ahmed-Aslam** [comment]
Sure, Thank you :)

**Pull request closed without merging**
