### PR TITLE
:fire: :bug: add pyiron_snippets to environment-notebooks-integration

### PR DESCRIPTION
**Pull request by liamhuber**
@samwaseda notebooks got ran when https://github.com/pyiron/pyiron_continuum/pull/317/files got merged and failed with "no module named `pyiron_snippets"

### CODE REVIEW

**Comment by liamhuber** [comment]
Multiple rolling failed, and it appears unrelated to this PR. @samwaseda could you help?

```
 Input Notebook:  notebooks/damask/multiplerolling.ipynb
Output Notebook: notebooks/damask/multiplerolling-out.ipynb

Executing:   0%|          | 0/28 [00:00<?, ?cell/s]Executing notebook with kernel: python3

Executing:   4%|▎         | 1/28 [00:00<00:22,  1.22cell/s]
Executing:  11%|█         | 3/28 [00:02<00:18,  1.32cell/s]
Executing:  50%|█████     | 14/28 [00:02<00:01,  8.41cell/s]
Executing:  71%|███████▏  | 20/28 [00:06<00:02,  2.95cell/s]
Executing:  71%|███████▏  | 20/28 [00:06<00:02,  2.89cell/s]
Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/my-env/bin/papermill", line 10, in <module>
    sys.exit(papermill())
             ^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/my-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/my-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/my-env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/my-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/my-env/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/my-env/lib/python3.11/site-packages/papermill/cli.py", line 235, in papermill
    execute_notebook(
  File "/home/runner/miniconda3/envs/my-env/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/runner/miniconda3/envs/my-env/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 8
      6 job.append_loading(load_steps=get_load_step(reduction_speed, reduction_height, reduction_outputs))
      7 job.input.regrid = True
----> 8 job.run()

File ~/miniconda3/envs/my-env/lib/python3.11/site-packages/pyiron_base/utils/deprecate.py:171, in Deprecator.__deprecate_argument.<locals>.decorated(*args, **kwargs)
    161     if kw in self.arguments:
    162         warnings.warn(
    163             message_format.format(
    164                 "{}.{}({}={})".format(
   (...)
    169             stacklevel=2,
    170         )
--> 171 return function(*args, **kwargs)

File ~/miniconda3/envs/my-env/lib/python3.11/site-packages/pyiron_base/jobs/job/generic.py:777, in GenericJob.run(self, delete_existing_job, repair, debug, run_mode, run_again)
    775     self._run_if_repair()
    776 elif status == "initialized":
--> 777     self._run_if_new(debug=debug)
    778 elif status == "created":
    779     self._run_if_created()

File ~/miniconda3/envs/my-env/lib/python3.11/site-packages/pyiron_base/jobs/job/generic.py:1298, in GenericJob._run_if_new(self, debug)
   1290 def _run_if_new(self, debug=False):
   1291     """
   1292     Internal helper function the run if new function is called when the job status is 'initialized'. It prepares
   1293     the hdf5 file and the corresponding directory structure.
   (...)
   1296         debug (bool): Debug Mode
   1297     """
-> 1298     run_job_with_status_initialized(job=self, debug=debug)

File ~/miniconda3/envs/my-env/lib/python3.11/site-packages/pyiron_base/jobs/job/runfunction.py:91, in run_job_with_status_initialized(job, debug)
     89     print("job exists already and therefore was not created!")
     90 else:
---> 91     job.save()
     92     job.run()

File ~/miniconda3/envs/my-env/lib/python3.11/site-packages/pyiron_base/jobs/job/generic.py:1170, in GenericJob.save(self)
   1168 if self._check_if_input_should_be_written():
   1169     self.project_hdf5.create_working_directory()
-> 1170     self.write_input()
   1171     _copy_restart_files(job=self)
   1172 self.status.created = True

File ~/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/damask/damaskjob.py:288, in DAMASK.write_input(self)
    284 def write_input(self):
    285     if self.input.regrid and len(self.input.job_names) > 0:
    286         self.input.grid = rgg.Regrid(
    287             self.input.grid, self.restart_file_list[0], self.input.regrid_scale
--> 288         ).grid
    289     self._write_loading()
    290     self._write_geometry()

File ~/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/damask/regrid.py:96, in Regrid.grid(self)
     94 @property
     95 def grid(self):
---> 96     material_rg = self.geom_0.material.flatten("F")[self.map_0to_rg].reshape(
     97         self.cells_rg, order="F"
     98     )
     99     return damask.GeomGrid(
    100         material_rg, self.size_rg, self.geom_0.origin, comments=self.geom_0.comments
    101     )

File ~/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/damask/regrid.py:83, in Regrid.map_0to_rg(self)
     80 @property
     81 def map_0to_rg(self):
     82     gridCoords_cell_rg = damask.grid_filters.coordinates0_point(
---> 83         self.cells_rg, self.size_rg
     84     ).reshape((-1, 3), order="F")
     85     # apply periodic shift
     86     grid_coords_cell_0_Shifted = self.grid_coords_cell_0 % self.size_rg

File ~/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/damask/regrid.py:72, in Regrid.cells_rg(self)
     69 @property
     70 def cells_rg(self):
     71     """regridded grid seeds"""
---> 72     seedSize_rg = np.min(self.size_rg / np.array(self.cells_0))
     73     if isinstance(self.seed_scale, float) or isinstance(self.seed_scale, int):
     74         return (self.seed_scale * np.round(self.size_rg / seedSize_rg)).astype(int)

File ~/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/damask/regrid.py:66, in Regrid.size_rg(self)
     56 cornersRVE_coords = np.diag(self.size_0)
     57 cornersRVE_idx = [
     58     np.argwhere(
     59         np.isclose(self.grid_coords_node_initial, cornersRVE_coords[corner]).all(
   (...)
     63     for corner in range(3)
     64 ]
     65 return (
---> 66     np.diag(self.grid_coords_node_0[cornersRVE_idx]) - self.grid_coords_node_0[0]
     67 )

File ~/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/damask/regrid.py:47, in Regrid.grid_coords_node_0(self)
     45 @property
     46 def grid_coords_node_0(self):
---> 47     return self.grid_coords_node_initial + self.d5Out.get("u_n") - self.d5Out.origin

File ~/miniconda3/envs/my-env/lib/python3.11/functools.py:1001, in cached_property.__get__(self, instance, owner)
    999 val = cache.get(self.attrname, _NOT_FOUND)
   1000 if val is _NOT_FOUND:
-> 1001     val = self.func(instance)
   1002     try:
   1003         cache[self.attrname] = val

File ~/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/damask/regrid.py:38, in Regrid.d5Out(self)
     35 @cached_property
     36 def d5Out(self):
     37     d5Out = damask.Result(self.load_name)
---> 38     d5Out = d5Out.view(increments=int(d5Out.increments[-1]))
     39     return d5Out

ValueError: invalid literal for int() with base 10: 'increment_250'
```

**Comment by samwaseda** [comment]
That's super strange. I don't get the same error. I also checked the content of `d5Out.increments[-1]` in multiple rolling, but I have only normal integers.

**Comment by samwaseda** [comment]
@tushar-jogi Maybe you have an idea? In short, the problem comes from the fact that the following code raises an error

```python
d5Out = damask.Result(file_name)
int(d5Out.increments[-1])
```

So in my setting `d5Out.increments[-1]` gives just a number (e.g. 250), while in GitHub CI it gives a string (e.g. `increment_250`), and we don't quite understand why it's happening.

**Comment by samwaseda** [comment]
I added a workaround, but I'm slightly uncomfortable with my solution

**Comment by samwaseda** [comment]
I merge this one because otherwise everything in continuum fails

**Comment by samwaseda** [comment]
@tushar-jogi commented that this error comes from the difference between 3.0.0b and 3.0.0a8, so I think we simply keep the fix I included, which would work in both cases.

**Pull request merged**
