### PR TITLE
Code abstraction damask

### PR DESCRIPTION
**Pull request by samwaseda**
I'm gonna make a series of changes for the code abstraction of Damask

### CODE REVIEW

**Comment by samwaseda** [comment]
```python
File ~/work/pyiron_continuum/pyiron_continuum/cached-miniforge/my-env/lib/python3.11/site-packages/pyiron_base/interfaces/has_dict.py:151, in HasDict.to_dict(self)
    149 data_dict = {}
    150 child_dict = {}
--> 151 for k, v in self._to_dict().items():
    152     if isinstance(v, HasDict):
    153         child_dict[k] = v.to_dict()

AttributeError: 'RectMesh' object has no attribute '_to_dict'
```

@pmrv @jan-janssen

**Comment by pmrv** [comment]
`pyiron_base=0.10.0` is still broken, this should be fixed with [this PR](https://github.com/pyiron/pyiron_base/pull/1632).

**Comment by samwaseda** [comment]
> `pyiron_base=0.10.0` is still broken, this should be fixed with [this PR](https://github.com/pyiron/pyiron_base/pull/1632).

So I should just downgrade it for now?

**Comment by samwaseda** [comment]
```
Executing:   0%|          | 0/37 [00:00<?, ?cell/s]Kernelspec name pyiron cannot be found!
No such kernel named pyiron
```

???

**Comment by mbruns91** [comment]
Ok, the failing execution of the DAMASK notebooks is related to them being (locally) created in an environment, where a non-standard kernel(name) like "pyiron" is used. I'll open a PR in [actions](https://github.com/pyiron/actions), to add the `-k python3` as optionally changeable argument.

Besides adapting the ci to use then the correct version of `build-notebooks`, nothing needs to be changed here.

**Pull request merged**
